# Generated by Django 5.1.3 on 2024-11-12 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(max_length=100)),
                ("unit_name", models.CharField(max_length=100)),
                ("unit_rental", models.IntegerField()),
                ("unit_address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RoomPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_name", models.CharField(max_length=255)),
                ("photo_path", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="UnitFileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="RoomDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=100)),
                ("best_case_rental", models.IntegerField()),
                ("worst_case_rental", models.IntegerField()),
                ("actual_rental", models.IntegerField(null=True)),
                ("is_rental", models.BooleanField(default=False)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.businessunit",
                    ),
                ),
            ],
        ),
    ]
