# Generated by Django 5.1.3 on 2024-11-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessunit",
            name="unit_address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
