# Generated by Django 5.1.3 on 2024-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyarea",
            name="area_description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
