# Generated by Django 5.1.3 on 2024-11-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_alter_businessunit_unit_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessunit",
            options={
                "verbose_name": "Business Unit",
                "verbose_name_plural": "Business Units",
            },
        ),
        migrations.AlterModelOptions(
            name="roomdetails",
            options={
                "verbose_name": "Room Detail",
                "verbose_name_plural": "Room Details",
            },
        ),
        migrations.AlterModelOptions(
            name="roomphoto",
            options={
                "verbose_name": "Room Photo",
                "verbose_name_plural": "Room Photos",
            },
        ),
        migrations.AlterModelOptions(
            name="unitfileattachment",
            options={
                "verbose_name": "Unit Attachment",
                "verbose_name_plural": "Unit Attachments",
            },
        ),
        migrations.AlterModelTable(
            name="businessunit",
            table="business_unit",
        ),
        migrations.AlterModelTable(
            name="roomdetails",
            table="room_details",
        ),
        migrations.AlterModelTable(
            name="roomphoto",
            table="room_photos",
        ),
        migrations.AlterModelTable(
            name="unitfileattachment",
            table="unit_attachment",
        ),
    ]
