# Generated by Django 5.1.3 on 2024-11-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_alter_propertyarea_area_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomphoto",
            name="photo_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
