# Generated by Django 5.1.3 on 2024-11-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_alter_businessunit_options_alter_roomdetails_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomphoto",
            name="business_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="unitfileattachment",
            name="business_unit",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="apps.businessunit",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roomdetails",
            name="business_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps.businessunit",
            ),
        ),
    ]
