apiVersion: v1
kind: Service
metadata:
  name: r2r-web-svc
  namespace: production
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: r2r-web