services:
  database:
    image: postgres:14-alpine
    container_name: spms_db
    env_file:
      - r2r-management/.env
    ports:
      - '5432:5432'
    volumes:
      - r2r-db-data:/var/lib/postgresql/data

volumes:
  r2r-db-data: